apiVersion: v1
kind: Service
metadata:
  name: user-commit-log-service
spec:
  selector:
    app: user-commit-log-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

