server:
  port: 8080
  servlet:
    context-path: /api/v1/user-commit-log-service

github:
  commit-detail-url: https://api.github.com/repos/EthicalML/awesome-production-machine-learning/contributors

spring:
  data:
    mongodb:
      uri: mongodb+srv://janani20231958:uESIWf8TL2LZeFPL@cluster0.dznm25o.mongodb.net/developer_iq_tracker

